import Vampire

-- The unused-variable linter cannot see through `vampire [*]`, which takes the whole
-- local context: every hypothesis below *is* used, just not by name in a proof term.
set_option linter.unusedVariables false
set_option linter.unusedSectionVars false

/-!
# Theorems from lean-smt

The `vampire` tactic is a port of a different pipeline, but it is aimed at the same
goals as `smt`, so lean-smt's own problems are a useful second opinion alongside the
TPTP sweep in `docs/STATUS.md`.

## What the paper actually benchmarks

*Lean-SMT: An SMT tactic for discharging proof goals in Lean* (Mohamed, Mascarenhas,
Khan, Barbosa, Reynolds, Qian, Tinelli, Barrett; CAV 2025) evaluates on two sets, §4:

* **5000 SMT-LIB benchmarks generated by Sledgehammer from Isabelle/HOL**, taken from
  *Seventeen Provers Under the Hammer* (Desharnais et al., ITP 2022). These stress the
  premise count — up to 512 lemmas per problem.
* **24 817 unsatisfiable SMT-LIB benchmarks from SMT-COMP 2024** in the fragments
  lean-smt supports: UF, IDL, RDL, LIA, LRA, LIRA, and their quantifier-free siblings.
  Of the 21 595 proofs cvc5 produced, lean-smt verified 15 271 (71%).

Both are `.smt2` files rather than Lean theorems, and only **UF** — uninterpreted
functions with equality and quantifiers — is inside what this tactic translates; the
arithmetic fragments are not (see `Vampire/Translate.lean`). The theorems below are
therefore taken from lean-smt's own test suite, which is Lean and is in that fragment:
`Test/Prop`, `Test/EUF` and `Test/Quant` of the lean-smt repository at revision
a934af2. `smt` is replaced by `vampire [*]`; nothing else is changed.
-/

namespace LeanSmt

/-! ## `Test/Prop` — the propositional core -/

theorem disjunctive_syllogism (p q : Prop) : p ∨ q → ¬p → q := by
  vampire [*]

theorem hypothetical_syllogism (p q r : Prop) : (p → q) → (q → r) → p → r := by
  vampire [*]

theorem modus_tollens (p q : Prop) : ¬q → (p → q) → ¬p := by
  vampire [*]

theorem resolution (p q r : Prop) : p ∨ q → ¬p ∨ r → q ∨ r := by
  vampire [*]

-- lean-smt's `Test/Prop` also has `cong (p q : Prop) (f : Prop → Prop) : p = q → f p = f q`.
-- That one is out of scope rather than unsupported: `f` takes a proposition as an
-- argument, which is higher-order, and Vampire's logic has no such sort. The tactic says
-- so — "a proposition cannot be the sort of an argument; the goal is higher-order".

/-! ## `Test/EUF` — equality with uninterpreted functions -/

/-- `Test/EUF/Example.lean`, the `smt [*]` form. Congruence feeding a propositional
refutation: exactly the shape the UF division is made of. -/
theorem euf_example {U : Type} [Nonempty U] {p1 p2 p3 : Prop} {f : U → U → U} {a b c d : U}
    (h0 : a = b) (h1 : c = d) (h2 : p1 ∧ True) (h3 : (¬p1) ∨ (p2 ∧ p3))
    (h4 : (¬p3) ∨ (¬(f a c = f b d))) : False := by
  vampire [*]

/-! ## `Test/Quant` — quantifier distribution -/

/-- `Test/Quant.lean`. An equality between propositions, which the translation reads as
`↔`, over three universals that have to be recombined. -/
theorem quant_distribution {U : Type} [Nonempty U] {p : U → Prop} :
    (∀ x y z, p x ∧ p y ∧ p z) = ((∀ x, p x) ∧ (∀ y, p y) ∧ (∀ z, p z)) := by
  vampire [*]

#print axioms euf_example
#print axioms quant_distribution
#print axioms resolution

end LeanSmt
