#!/usr/bin/env python3
"""Regenerates Vampire/InferenceRule.lean from vampire's Inference.hpp.

  ./scripts/gen-inference-rules.py ../vampire-fork
"""
import re
import subprocess
import sys

LEAN_KEYWORDS = {
    "axiom", "def", "theorem", "instance", "end", "exists", "forall", "fun",
    "have", "let", "match", "with", "do", "if", "then", "else", "from",
    "structure", "class", "where", "deriving", "open", "section", "namespace",
    "variable", "universe", "set_option", "example", "mutual", "partial",
    "unsafe", "private", "protected", "true", "false", "and", "or", "not",
    "in", "at", "by", "calc", "show", "this", "sorry", "rec", "type",
}


def camel(name: str) -> str:
    head, *rest = name.lower().split("_")
    ident = head + "".join(word.capitalize() for word in rest)
    return f"«{ident}»" if ident in LEAN_KEYWORDS else ident


def main() -> int:
    root = sys.argv[1] if len(sys.argv) > 1 else "../vampire-fork"
    header = f"{root}/Kernel/Inference.hpp"
    body = re.search(
        r"enum class InferenceRule : unsigned char \{(.*?)\n\};",
        open(header).read(),
        re.S,
    )
    if body is None:
        print(f"could not find InferenceRule in {header}", file=sys.stderr)
        return 1
    if re.search(r"^\s*([A-Z][A-Z_0-9]*)\s*=", body.group(1), re.M):
        print("InferenceRule now assigns explicit values", file=sys.stderr)
        return 1
    names = re.findall(r"^\s*([A-Z][A-Z_0-9]*)\s*,", body.group(1), re.M)
    if len(names) != len(set(names)):
        print("InferenceRule has duplicate names", file=sys.stderr)
        return 1
    commit = subprocess.run(
        ["git", "-C", root, "rev-parse", "--short", "HEAD"],
        capture_output=True, text=True,
    ).stdout.strip()

    out = [
        "-- Generated by scripts/gen-inference-rules.py from vampire's",
        f"-- Kernel/Inference.hpp at {commit}. Do not edit.",
        "",
        "namespace Vampire",
        "",
        "/-- Vampire's `Kernel::InferenceRule`, in declaration order. -/",
        "inductive InferenceRule where",
    ]
    out += [f"  | {camel(n)}" for n in names]
    out += [
        "deriving Inhabited, Repr, BEq, DecidableEq",
        "",
        "namespace InferenceRule",
        "",
        f"/-- How many rules vampire declares. -/",
        f"def count : Nat := {len(names)}",
        "",
        "/-- The rules, indexed as vampire numbers them. -/",
        "def all : Array InferenceRule :=",
        "  #[" + ", ".join("." + camel(n) for n in names) + "]",
        "",
        "/-- Vampire's own name for a rule. -/",
        "def name : InferenceRule → String",
    ]
    out += [f"  | .{camel(n)} => \"{n.lower()}\"" for n in names]
    out += [
        "",
        "instance : ToString InferenceRule := ⟨name⟩",
        "",
        "/-- The rule vampire numbers `i`. -/",
        "def ofNat? (i : Nat) : Option InferenceRule := all[i]?",
        "",
        "end InferenceRule",
        "",
        "end Vampire",
        "",
    ]
    open("Vampire/InferenceRule.lean", "w").write("\n".join(out))
    print(f"wrote Vampire/InferenceRule.lean with {len(names)} rules")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
